name: Workflow On Call - Manual Release
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      
      message:
        required: true
        type: string


jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  deploy2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  deploy3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"

  deploy4:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ inputs.environment }}"
      - run: echo "${{ inputs.message }}"